//Le paso el id del user que tengo en la BD
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV6ZW0iLCJpZCI6IjY3ZjE5ZjlhOWMyYTI3OTM3MjQzYTFiYyIsImlhdCI6MTc0Mzg5NjA5N30.faf4rVwi308Y4tYxFBtoEYeJmVOsU6o_klaY6IX616w

{
  "title": "Probando eliminar blog solo con token",
  "author": "Eze",
  "url": "eze.com/eliminarcontoken",
  "likes": 42
}